import React from "react";
import { Link } from "react-router-dom";

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-background text-foreground px-5 py-10">
      <div className="mx-auto max-w-3xl">
        <div className="mb-8">
          <Link to="/login" className="text-sm text-primary hover:underline">Art Flow Creative</Link>
          <h1 className="mt-3 text-3xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mt-2 text-sm text-muted-foreground">Effective date: August 29, 2026</p>
        </div>

        <div className="space-y-7 text-sm leading-7">
          <section>
            <p>
              These Terms of Service govern your use of Art Flow Creative, a business-management application for artists and creative sellers. By creating an account or using the service, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Use of the service</h2>
            <p>
              You may use Art Flow Creative to manage business information such as orders, inventory, expenses, mileage, reports, schedules, and connected-service data. You are responsible for the accuracy of information you enter or import and for using the service in compliance with applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Your account</h2>
            <p>
              You are responsible for maintaining the security of your login credentials and for activity that occurs through your account. You should promptly report suspected unauthorized access and keep your account information current.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Connected services</h2>
            <p>
              Art Flow Creative may allow you to connect third-party services such as Google Sheets or Gmail. Connecting a service is optional. When you authorize a connection, you permit Art Flow Creative to access only the permissions requested for the feature you choose to use. Third-party services are also governed by their own terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Your content and business data</h2>
            <p>
              You retain ownership of the business information and content you provide to Art Flow Creative. You grant the service permission to process that information only as necessary to operate, synchronize, display, back up, and support the features you use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Acceptable use</h2>
            <p>
              You may not misuse the service, attempt to gain unauthorized access to another user's account or data, interfere with the service, upload malicious code, use the app for unlawful activity, or attempt to circumvent security or access controls.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Availability and changes</h2>
            <p>
              Features may be updated, added, changed, or discontinued as Art Flow Creative evolves. While reasonable efforts are made to keep the service available and accurate, uninterrupted availability is not guaranteed.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Business calculations and reports</h2>
            <p>
              Totals, profit estimates, tax estimates, inventory calculations, and reports generated by Art Flow Creative are tools for business organization and are not legal, tax, accounting, or financial advice. You are responsible for reviewing your records and consulting a qualified professional when appropriate.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Disclaimers</h2>
            <p>
              Art Flow Creative is provided on an "as is" and "as available" basis to the extent permitted by law. No warranty is made that every feature will be error-free or that imported third-party data will always be complete or current.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Limitation of liability</h2>
            <p>
              To the extent permitted by law, Art Flow Creative and its owner will not be liable for indirect, incidental, special, consequential, or business-loss damages arising from use of or inability to use the service, third-party service interruptions, or inaccurate information supplied by users or connected services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Termination</h2>
            <p>
              You may stop using the service at any time. Access may be suspended or terminated for misuse, security risks, unlawful activity, or material violations of these terms. Where available, you may request deletion of your account and associated data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Changes to these terms</h2>
            <p>
              These terms may be updated as the service changes. Continued use after updated terms become effective constitutes acceptance of the revised terms where permitted by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Contact</h2>
            <p>
              Questions about these Terms of Service may be directed to the Art Flow Creative app owner through the support contact associated with the application.
            </p>
          </section>
        </div>

        <div className="mt-10 border-t border-border pt-6 flex flex-wrap gap-4 text-sm">
          <Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link>
          <Link to="/login" className="text-primary hover:underline">Return to login</Link>
        </div>
      </div>
    </main>
  );
}
